language: python
python:
  - "3.7"
before_install:
install:
  - pip install -r requirements-ci.txt -t vendored
before_script:
  - python handler.py
script:
  - ./test/pytest
after_success:
after_failure:
